version: '3.7'

services:

  birracraft:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: birracraft
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/birracraft
    ports:
      - 8000:8000
    networks:
      birracraft-net:
