version: '3.7'

services:

  api:
    build:
      context: ./src
      target: builder
    container_name: birracraft-api
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./src:/usr/src/birracraft
    depends_on:
      db:
        condition: service_healthy
    restart: "always"
    networks:
      birracraft-net:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: birracraft-web
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/src/web
    depends_on:
      - api
    restart: "always"
    networks:
      birracraft-net:

  mailhog:
    image: mailhog/mailhog
    container_name: birracraft-mailhog
    ports:
      - 1025:1025  # SMTP Server
      - 8025:8025  # Web UI
    restart: "always"
    networks:
      birracraft-net:
