version: '3.7'

services:

  api:
    build:
      context: ./src
      target: builder
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./src:/usr/src/birracraft

  worker:
    build:
      context: ./src
      target: server_celery
    command: celery -A birracraft worker -l INFO
    volumes:
      - ./src:/usr/src/birracraft

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/usr/src/web

  mailhog:
    image: mailhog/mailhog
    container_name: birracraft-mailhog
    ports:
      - 1025:1025  # SMTP Server
      - 8025:8025  # Web UI
    restart: "always"
    networks:
      birracraft-net:
