version: '3.7'

services:

  api:
    build:
      context: ./src
      target: base
    container_name: birracraft-api
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - static_volume:/static
    depends_on:
      db:
        condition: service_healthy
    restart: "always"
    networks:
      birracraft-net:

  nginx:
    image: nginx:1.19.0-alpine
    container_name: birracraft-nginx
    ports:
      - "6868:80"
      - "8686:86"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - api
      - web
    restart: "always"
    networks:
      birracraft-net:

  db:
    image: postgres:14-alpine3.15
    container_name: birracraft-pgsql
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 15s
      retries: 10
    restart: "always"
    networks:
      birracraft-net:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: birracraft-web
    expose:
      - 3000
    depends_on:
      - api
    restart: "always"
    networks:
      birracraft-net:


volumes:
  pgsql_data:
  static_volume:

networks:
  birracraft-net: